# Generated by Django 5.2.3 on 2025-06-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
